### ISSUE TITLE
Search bar does not work

### ISSUE THREAD

**Issue by morrisseydylan** [HexedHero/FandomForceHydra#1]
Clicking on links within a wiki page works fine. However using the search bar on a wiki does not work. What I did:

1) Enter https://minecraft.fandom.com/. I got redirected to https://minecraft.fandom.com/wiki/Minecraft_Wiki?useskin=hydra (working as expected)

2) Enter "stone" in the top-right search bar. I got redirected to https://minecraft.fandom.com/wiki/Stone and then was redirected to https://www.fandom.com/silver-surfer.html?useskin=hydra, which is a blank page. I have no idea why this happens.

Also, searching for a term that doesn't direct you to page with its name (like searching for "stone" should bring me to the Stone page) doesn't work either. For example, entering "aa" in the search bar brings me to https://minecraft.fandom.com/wiki/Special:Search?search=aa&go=Go%3Fuseskin%3Dhydra, a page with the unchanged Fandom layout. Perhaps this is because the website is changing the `?` and `=` characters in `?useskin=hydra` to `%3F` and `%3D` respectively.

I also tested this on the Temtem wiki and got the same results. This was done on Microsoft Edge version 92.0.902.62 (Chromium).

**Comment by HexedHero** [comment]
Should be fixed in 1.1.0, currently pending review. Thank you.
