### ISSUE TITLE
Firefox or TamperMonkey?

### ISSUE THREAD

**Issue by rbits0** [HexedHero/FandomForceHydra#2]
Fandom has now made it so that you can't enable the hydra skin in settings. The only way to do it now is to add ?usekin=hydra to the url. But when you can't use it like that, because when you click on a link, it goes back to the old style. Can you port this to firefox or make a tampermonkey script? Or do you know of something that exists? I've spent the past hour trying to revert to the old wiki and I can't.

**Comment by HexedHero** [comment]
Honestly, it's just a lost cause. Most wikis are just starting to force the new theme so within a few weeks hydra will be completely gone. Unless someone makes a custom theme that works on all wikis but no one has that time.
